### ISSUE TITLE
Unable to return to main menu, must reboot talespire

### ISSUE THREAD

**Issue by PanoramicPanda** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#18]
Can't find a way to return to the menu in case I want to switch campaigns

**Comment by cbaggers** [comment]
Confirmed. Internal ticket https://github.com/Bouncyrock/TaleSpire/issues/415

Thanks, we'll keep ya posted

**Comment by PanoramicPanda** [comment]
Saw fix in latest build. Closing.
