### ISSUE TITLE
Some tile are misnamed

### ISSUE THREAD

**Issue by cbaggers** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#25]
**Describe the bug**
Some of these tiles seem wrong

![wrong names](https://user-images.githubusercontent.com/1579326/51015199-96f78a80-156b-11e9-8b85-22c7fc442787.png)

**Comment by cbaggers** [comment]
Actually the names seem right. It's the assets that are wrong

**Comment by cbaggers** [comment]
OH, the tiles are changing over time..weird

**Comment by MarcLobster** [comment]
Confirming that the tiles seem to change even while the program is open. In one instance, it changed after closing and opening the drop down menu for Tiles. Will try to get back to this with a clip from Twitch when I find it

**Comment by cbaggers** [comment]
Thanks @Eat2surf, good to know

**Comment by cbaggers** [comment]
Fix for this was pushed out. Closing.

Please let me know if you are still seeing changing assets and we will reopen this
