### ISSUE TITLE
Can't close the game

### ISSUE THREAD

**Issue by LittleCodingFox** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#40]
**Describe the bug**
My DM was unable to connect to my campaign, and I tried to close the game. It got stuck and won't close.

**To Reproduce**
1. Play and maybe get a state bug
2. Try to close the game
3. Click yes to close and sync

**Comment by cbaggers** [comment]
Confirmed. We have a patch for this internally. It will be out in the next update

Thanks for reporting!

**Comment by cbaggers** [comment]
@LittleCodingFox we have an update out now that should fix this. If you have time to retest this it would be very appreciated!

**Comment by LittleCodingFox** [comment]
Can confirm it works! Closing now 👍
