### ISSUE TITLE
Asset selection drop down menu does not properly populate

### ISSUE THREAD

**Issue by ThomasMcHale** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#44]
**Describe the bug**
I minimized and reopened the drop down menu for the Tavern Set and the re-opened menu did not populate properly. Reopening the menu added ~2-3 assets each time.

**To Reproduce**
Unsure how to reproduce

**Screenshots/Videos/Twitch Clips**
https://clips.twitch.tv/HilariousLazyDonkeyBabyRage

**Comment by cbaggers** [comment]
Heya @ThomasMcHale a new update is out which should fix this. If you are able to test this again that would be a big help.

**Comment by ThomasMcHale** [comment]
Not seeing the bug anymore. Seems fixed.

**Comment by cbaggers** [comment]
woo!
