### ISSUE TITLE
Mouse cursor not constrained by window, even in fullscreen mode

### ISSUE THREAD

**Issue by ryvaeus** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#45]
**Describe the bug**
When moving the mouse cursor outside the borders of the TaleSpire window, even if TaleSpire is in fullscreen mode, the cursor can escape the window. This is most evident in dual/multi-screen setups, and leads to such issues as rotating or panning the camera causing Windows to lose focus on TaleSpire due to the natural mouse movement of these activities causing the cursor to go out of bounds.

**To Reproduce**
1. Move mouse outside of TaleSpire window
2. Click
3. TaleSpire loses focus and is minimized

**Screenshots/Videos/Twitch Clips**
https://gfycat.com/GrandFrequentKestrel

**Additional context**
Most noticeable with dual/multi-monitor setups, as the bug happens even in full screen mode. Probably due to Unity's implementation of "full screen" which is actually borderless windowed mode. Annoying nonetheless.

**Comment by cbaggers** [comment]
Thanks for the report. Tracking this internally https://github.com/Bouncyrock/TaleSpire/issues/442

We were using Unity's software cursor for a while but back then we had some issue that made it a major pita. We'll have a look to see what we can do about this.

**Comment by cbaggers** [comment]
@ryvaeus in the latest update we are using borderless windowed mode for fullscreen which should help in that case. You should be able to click on, say, a different monitor and the game shouldnt minimize. Same goes for tabbing between windows.

Not a true fix to the original issue so I'm keeping this open, but I hope this helps.

**Comment by ryvaeus** [comment]
Can confirm, mousing to second window and clicking no longer minimizes TS.
