### ISSUE TITLE
TaleSpire Fails To Close When Request is Initiated Through Steam

### ISSUE THREAD

**Issue by MrMonop** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#46]
**Describe the bug**
Changed a setting in Steam (specifically where screenshots are stored). Steam required a restart and tried to close TaleSpire. Went into TaleSpire which wanted a confirmation of closing and syncing board. Clicked yes and TaleSpire keeps syncing but not closing. Yes button can be toggled at this point. Only upon clicking "NO" does it bring me back into TaleSpire where I was in Builder Mode. (Yes Toggle shown in screenshots below).

**To Reproduce**
1. Change a Steam setting with TaleSpire Open that requires a restart of Steam and closing of TaleSpire
2. Enter TaleSpire and click "YES"
3. Watch the board sync, "YES" can be toggled
4. "Click "NO" instead and exit back to normal TaleSpire

**Screenshots/Videos/Twitch Clips**

![20190111221859_1](https://user-images.githubusercontent.com/39739633/51068690-c64fdb00-15ef-11e9-95e0-fee83d1300fb.jpg)
![20190111221906_1](https://user-images.githubusercontent.com/39739633/51068692-ccde5280-15ef-11e9-8b24-e4fe55db4c97.jpg)
![20190111221902_1](https://user-images.githubusercontent.com/39739633/51068691-cbad2580-15ef-11e9-8e2b-2861c79ad0d3.jpg)

**Additional context**
-I was in Builder Mode when it happened
-I changed the Steam Screenshot storage location

**Comment by cbaggers** [comment]
Excellent report, thanks for all the info.

I think this a side effect of other bugs. If so then it is the same as [this ticket](https://github.com/Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker/issues/40). 

We have a patch for that internally that will be out in the next update so when that comes out we can try this again

**Comment by cbaggers** [comment]
@MrMonop an update is out now that should help this. If you have the time to test this again it would be super helpful!

**Comment by MrMonop** [comment]
@cbaggers the issue for this seems to be fixed now, thanks for the quick update!

**Comment by cbaggers** [comment]
Great! Thanks for the follow up
