### ISSUE TITLE
Ambient lighting stacks rather than replaces prior 'atmospheric' lighting

### ISSUE THREAD

**Issue by RPGKenL** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#47]
**Describe the bug**
Changing ambient lighting tends to stack atop others. To get accurate mood lighting, one has to reset to default prior to selecting another light/atmospheric setting.

**To Reproduce**
Choose atmospheric lighting settings sequentially.

**Screenshots/Videos/Twitch Clips**
https://streamable.com/rerge

**Additional context**
In the clipped video above, note that the "magic" mood for the dungeon atmosphere should be purple rather than the washed out appearance after all the mood lighting changes.

It's only after I reset to default, then again choose "magic" that it appears purple.

**Comment by cbaggers** [comment]
Thanks @RPGKenL, excellent report. Just so I make sure I understand do you always see the lighting mixing, or does it only happen occasionally?

**Comment by RPGKenL** [comment]
It happens reliably when switching ambient moods. The more profound the difference in lighting, the more noticeable the distortion.

**Comment by cbaggers** [comment]
I've got a fix for this internally. There's a good chance it will be in the next update

**Comment by cbaggers** [comment]
This shipped a few days back. Should be fixed now. Please reopen if you see this issue again.
