### ISSUE TITLE
Build mode editor enters strange state when drag-building segments that end on a die icon

### ISSUE THREAD

**Issue by RPGKenL** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#48]
**Describe the bug**
When in build mode, if dragging a long section of floor/wall, if the cursor ends above a die icon and the mouse is release, the editor enters a 'floating' or unknown state

**To Reproduce**
1. Draw long segment ending mouse cursor over any die/dice icon
2. Release mouse drag

**Screenshots/Videos/Twitch Clips**
https://streamable.com/swpnf

**Comment by PanoramicPanda** [comment]
Duplicate of #20. Suggest closing.

**Comment by cbaggers** [comment]
Thank for the report @RPGKenL, great video too, I'm going to close this so we dont have duplicates but will link your video for the other ticket.
