### ISSUE TITLE
Line of sight indicators show for creatures on all floors.

### ISSUE THREAD

**Issue by cbaggers** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#61]
**Describe the bug**
When I right click on a creature to view line of sight I see indicators for all floors.

**To Reproduce**
1. set up multiple floors with creatures on each floor
2. right click a creature on lowest floor
3. note that indicators are showing for creature we couldnt possibly see

**Comment by ryvaeus** [comment]
Here's video confirmation from my end:

Floor 1 to Floor 2: https://clips.twitch.tv/HonorableBlazingChinchillaDatSheffy
Floor 2 to Floor 1: https://clips.twitch.tv/SpookyYawningSparrowPartyTime

**Comment by cbaggers** [comment]
Thanks @ryvaeus. The tweaks I've made to the current line of sight setup fix this and those should be out in the next update. I'll post back here when it is so we can test it again

**Comment by cbaggers** [comment]
This should have been fixed in a recent update. It would be ace if you could test this again. Cheers!

**Comment by cbaggers** [comment]
gonna pull a 'works for me' and close this one :)
