### ISSUE TITLE
[Suggestion] Layers below

### ISSUE THREAD

**Issue by AlexanderWardlow** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#78]
Just as my title suggests. I was halfway through building a castle and decided to start work on the most important (to my rpg game) part, the dungeon. I soon realized that I could not move layers, nor could I spawn one bellow layer 1. Therefore I am stuck with a castle on layer 1, and either have to recreate it or not have a dungeons entirely. This is probably something you were planing on adding anyway, and I am not complaining (I know its alpha), just showing you a reason to have this functionality in case you did not think to add it.

**Comment by cbaggers** [comment]
The current approach to floors doesn't allow this as each floor is (essentially) infinitely wide. This means that moving/deleting/etc would affect every building in a town (for example).

We are reworking the floor system now and that will allow for more of these kinds of controls.

As this is a feature request I'm gonna close it for now but thanks for letting us know! We'll keep you posted as fixes come
