### ISSUE TITLE
Characters can't walk behind Mourngoth Wall 01

### ISSUE THREAD

**Issue by ryvaeus** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#82]
**Describe the bug**
Tried to make a 1-width hallway behind a room that used Wall 01 tiles. Turns out figurines couldn't walk on this hallway until I replaced the Wall 01 tiles with literally any other wall.

**To Reproduce**
1. Lay down a Wall 01 tile from the Mourngoth set
2. Put a 2x1 or two 1x1 floor tiles behind it, then any other wall - even Wall 02 from the same tileset - with its back facing the floor tiles so you make a makeshift 2x1 hallway between the two walls
3. Try putting a figurine in that hallway
4. Now, replace Wall 01 with any other wall and attempt to place a figurine in the hallway again

**Screenshots/Videos/Twitch Clips**
https://clips.twitch.tv/ArtsyMistyIguanaBloodTrail

**Comment by Jclef** [comment]
Fixed
