### ISSUE TITLE
Able to move characters 1 more tile than Visible

### ISSUE THREAD

**Issue by Mercer01** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#91]
**Describe the bug**
You can move further than intended

**To Reproduce**
1.  Move character 
2. Video below shows it better

**Screenshots/Videos/Twitch Clips**
 https://youtu.be/_5gfl6eGWLU

**Additional context**
Unburden yourself of thoughts and musings here

**Comment by cbaggers** [comment]
Great report! I'll merge it with this existing one though https://github.com/Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker/issues/27

Thanks!
