### ISSUE TITLE
Most of map Missing on load

### ISSUE THREAD

**Issue by BlappoSpawn** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#94]
**Describe the bug**
I tried to load one of my first maps, to do some bug hunting. lucky me when i opened it i lost most of the map.

there should be 2 taverns each 2 stories and a full wall and fields with hills. below is what is left.

**To Reproduce**
Steps to reproduce the behavior are still being hunted please help.
1. build a board
2. save board
n. ??
n+1. open board many days later.

**Screenshots/Videos/Twitch Clips**
![screenshot 64](https://user-images.githubusercontent.com/46600569/51802644-1c409780-221a-11e9-940d-51711dae1978.png)

**Additional context**
I will add that i opened the map more than once, the first time my 2nd story didnt load however the 2nd floor button was visable. when i clicked to load the map again, it no longer has a 2nd floor button leading me to believe my second floor is actually gone.

**Comment by BlappoSpawn** [comment]
here is another map, this one the WHOLE map is empty.
![screenshot 65](https://user-images.githubusercontent.com/46600569/51802751-f4056880-221a-11e9-96fd-a5cfd9d6d755.png)

notice the map is named. this is a loaded map.

**Comment by cbaggers** [comment]
Ok it seems to be chunk related
> Baggers: hard to phrase the question, but if there stuff missing from the areas that are visible, or is it that whole chunks are missing?
> ..trimmed..
> [4:17 PM] Blappo: yes what is visible in the partial map everything is how i expect

**Comment by cbaggers** [comment]
Got a stack trace logged that suggests a deserialization failure when loading a tile.. no more good info though.

I'm gonna write some code on the backend to clone board files into other campaigns so I can test on my machine.

We have three parts to this issue:

1. The deserialize failure
2. The fact that the failure wasnt handled 
3. The fact that the board syncd after the failure happend

**Comment by cbaggers** [comment]
We have found the source of the bug. It's based on the serialization code making an assumption as to how boardAssets are updated.

We will likely put at a patch update to get us back to where we were and then make a proper fix to the serialization code

**Comment by cbaggers** [comment]
I'm late to update this. Patch when out. Fix is ready and will be pushed soon

**Comment by cbaggers** [comment]
Fix is out. Please ping me if you want damaged boards restored.

Thanks once again for all your help narrowing down this issue
