### ISSUE TITLE
Castle MournGoth combat music to left instead of at top

### ISSUE THREAD

**Issue by Mercer01** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#96]
**Describe the bug**
Incredibly Minor see pictures

**To Reproduce**
1. Place Down castle Mourgoth atmosphere
2. See that unlike the rest its to the right instead of at the top

**Screenshots/Videos/Twitch Clips**
![image](https://user-images.githubusercontent.com/14834963/51855639-a0337600-2325-11e9-8538-0e0bd804c49d.png)
![image](https://user-images.githubusercontent.com/14834963/51855654-b04b5580-2325-11e9-97d2-fac41d3ce3cc.png)

**Comment by cbaggers** [comment]
Thanks for reporting. This isn't a bug though. It's just where it ends up given that the items are spread evenly round the point.
